/**
 * Profile id management — survives page refresh via localStorage.
 *
 * Mirrors the session.ts convention. The profile_id is a UUID4 generated by
 * the backend when the wizard is submitted; clients store it and send it on
 * subsequent /chat calls so the agent can personalise the plan.
 *
 * A separate `dismissed` key tracks "user explicitly skipped the wizard" so
 * we don't keep re-prompting them on every refresh.
 */

const PROFILE_KEY = "ctp:profile_id";
const DISMISSED_KEY = "ctp:wizard_dismissed";

export function loadProfileId(): string | null {
  if (typeof window === "undefined") return null;
  try {
    return window.localStorage.getItem(PROFILE_KEY);
  } catch {
    return null;
  }
}

export function saveProfileId(id: string): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(PROFILE_KEY, id);
  } catch {
    // localStorage unavailable — fall through; profile becomes session-scoped.
  }
}

export function clearProfileId(): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.removeItem(PROFILE_KEY);
  } catch {
    // see above
  }
}

export function loadWizardDismissed(): boolean {
  if (typeof window === "undefined") return false;
  try {
    return window.localStorage.getItem(DISMISSED_KEY) === "1";
  } catch {
    return false;
  }
}

export function saveWizardDismissed(): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem(DISMISSED_KEY, "1");
  } catch {
    // see above
  }
}

export function clearWizardDismissed(): void {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.removeItem(DISMISSED_KEY);
  } catch {
    // see above
  }
}
