"""SQLModel ORM tables.

Tool data (5 tables, one per kind of reference data):
  - routes / waypoints      — get_route corridors
  - accommodations          — find_accommodation per-city catalog
  - weather_norms           — get_weather (per location, per month)
  - elevation_segments      — get_elevation_profile (per start→end pair)

User data (Phase 2D — added 2026-05-09):
  - user_profiles           — onboarding profile (experience, priorities,
                              dietary, etc.) used to personalise the agent's
                              planning per turn. Persisted across sessions.

Design notes:
  - All string lookups (city names, segment endpoints, profile_id) are
    normalized to lowercase and indexed. Normalization happens in tool /
    endpoint functions so the column convention is "lowercase already."
  - Literal/enum types from `src.tools.schemas` and `src.api.schemas` are
    stored as plain strings; Pydantic re-validates at the boundary so
    invalid values can't survive a round-trip.
  - List-valued profile fields (`trip_styles`, `priorities`, `dietary`)
    are JSON-serialised as TEXT for SQLite test compatibility — Postgres
    JSON columns would be richer but break the SQLite in-memory fixture.
  - We don't use Alembic for migrations yet — this is a case study, and
    `SQLModel.metadata.create_all()` (called by db.init_db) is sufficient.
"""

from __future__ import annotations

from datetime import datetime, timezone

from sqlmodel import Field, SQLModel


class Route(SQLModel, table=True):
    """A canonical corridor between two cities.

    Waypoints are queried separately by route_id rather than via
    ORM Relationship — keeps SQLModel's typing simple and avoids the
    `Mapped[]` annotation requirement that SQLAlchemy 2.x adds for
    bidirectional relationships.
    """

    __tablename__ = "routes"

    id: int | None = Field(default=None, primary_key=True)
    start_lower: str = Field(index=True, description="Lowercased start city, used for lookups")
    end_lower: str = Field(index=True, description="Lowercased end city")
    start_display: str
    end_display: str
    total_distance_km: float
    notes: str | None = None


class Waypoint(SQLModel, table=True):
    """A single ordered point along a Route.

    Linked to its parent Route via `route_id` (foreign key). Tools query
    waypoints by `route_id` and `sequence` rather than via a relationship,
    which keeps the data access pattern explicit.
    """

    __tablename__ = "waypoints"

    id: int | None = Field(default=None, primary_key=True)
    route_id: int = Field(foreign_key="routes.id", index=True)
    sequence: int = Field(description="Order within the route, 0-indexed")
    name: str
    country: str
    distance_from_start_km: float
    is_ferry_required: bool = False


class Accommodation(SQLModel, table=True):
    """A single place to stay near a city."""

    __tablename__ = "accommodations"

    id: int | None = Field(default=None, primary_key=True)
    location_lower: str = Field(index=True)
    name: str
    type: str = Field(description="camping | hostel | hotel | guesthouse")
    location: str
    distance_from_location_km: float
    estimated_price_eur_per_night: float
    bike_friendly: bool = True
    notes: str | None = None


class WeatherNorm(SQLModel, table=True):
    """Climate norm for a single (location, month) pair."""

    __tablename__ = "weather_norms"

    id: int | None = Field(default=None, primary_key=True)
    location_lower: str = Field(index=True)
    month: str = Field(index=True, description="Full month name e.g. 'June'")
    avg_temp_celsius: float
    avg_high_celsius: float
    avg_low_celsius: float
    rain_days_per_month: int
    avg_rain_mm: float
    notes: str | None = None


class ElevationSegment(SQLModel, table=True):
    """Terrain profile between two adjacent points."""

    __tablename__ = "elevation_segments"

    id: int | None = Field(default=None, primary_key=True)
    start_lower: str = Field(index=True)
    end_lower: str = Field(index=True)
    distance_km: float
    elevation_gain_m: int
    elevation_loss_m: int
    max_grade_percent: float
    difficulty: str = Field(description="easy | moderate | hard | extreme")
    notes: str | None = None


# ---------------------------------------------------------------------------
# Phase 2D · User profile (driven by cyclist user research, 2026-05-09)
# ---------------------------------------------------------------------------


class UserProfileRow(SQLModel, table=True):
    """Cyclist profile collected via the onboarding wizard.

    The agent fetches this on every /chat call (when `profile_id` is sent in
    the request) and injects a personalisation fragment into the system
    prompt — so it knows what fitness level, priorities, and dietary needs
    to plan around.

    `profile_id` is a UUID4 generated by the client and persisted in
    localStorage. Same id can be reused across sessions, so the agent
    remembers the rider across trips.

    List fields are JSON-serialised TEXT (not Postgres ARRAY/JSONB) so the
    SQLite in-memory test fixture works with the same schema.
    """

    __tablename__ = "user_profiles"

    id: int | None = Field(default=None, primary_key=True)
    profile_id: str = Field(
        index=True, unique=True, description="UUID4, generated client-side"
    )

    # Cycling experience — the keystone field. Drives `max_daily_km_comfort`
    # and the agent's "don't push past their comfort distance unsolicited" check.
    experience: str = Field(
        description="beginner | casual | intermediate | experienced | racer"
    )
    max_daily_km_comfort: int = Field(ge=20, le=300)

    # Multi-select fields — JSON-serialised lists.
    trip_styles_json: str = Field(
        default="[]", description="JSON list of: weekend, touring, commute, charity, special, solo"
    )
    priorities_json: str = Field(
        default="[]",
        description=(
            "JSON list of priorities (max 3). Options: scenery, distance, "
            "food_drink, wild_camping, quiet_roads, pubs_culture, cheap, iconic, photography"
        ),
    )
    dietary_json: str = Field(
        default="[]",
        description="JSON list: vegetarian, vegan, gluten_free, halal, kosher, lactose_free, none",
    )

    additional_notes: str | None = Field(
        default=None,
        max_length=500,
        description="Free-text — 'cycling for charity', 'have asthma', etc.",
    )

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ---------------------------------------------------------------------------
# Phase 1.12b · Session store — Cloud Run cold-starts wipe in-memory dicts
# ---------------------------------------------------------------------------


class SessionRow(SQLModel, table=True):
    """Persisted ConversationState — the agent loop's memory across requests.

    The whole ConversationState is serialised to JSON (TEXT) rather than mapped
    field-by-field. ConversationState is Pydantic top-to-bottom (messages,
    trace events, token counters), so a JSON blob is loss-free and lets us
    evolve the state schema without touching the SQLModel.

    Why we didn't relationally model trace events:
      - Trace events are append-only and consumed in-order. Relational
        querying would mean N+1 fetches per /trace call. JSON blob is one
        row, one parse.
      - Anthropic's `messages` content-block format (text, tool_use,
        tool_result, image) is nested and recursive — relational
        decomposition would be 3+ tables for one thread. Lossy round-trips
        inevitable.
      - We never search inside a session — only fetch by session_id and
        update the whole thing. Document-shape is the right shape.

    Same datetime convention as `UserProfileRow`: tz-aware UTC at the
    Pydantic boundary, naive UTC in Postgres `TIMESTAMP WITHOUT TIME ZONE`.
    """

    __tablename__ = "sessions"

    id: int | None = Field(default=None, primary_key=True)
    session_id: str = Field(
        index=True, unique=True, description="UUID4 — the same id the agent emits"
    )
    state_json: str = Field(
        description="ConversationState serialised via .model_dump_json()"
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
